apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres/00-namespace.yaml
  - postgres/01-secret.yaml
  - postgres/02-deployment.yaml
  - postgres/03-service.yaml
  - redis/04-redis-deployment.yaml
  - redis/05-redis-service.yaml
  - app/06-configmap.yaml
  - app/07-secret.yaml
  - app/08-deployment.yaml
  - app/09-service.yaml
  - app/10-pdb.yaml