apiVersion: v1
kind: Service
metadata:
  name: ufocache-service
  namespace: ufology
  labels:
    app: ufocache
spec:
  type: ClusterIP
  selector:
    app: ufocache
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379